# Generated by Django 5.0.14 on 2026-05-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0003_remove_pedido_productos_pedidoitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="destino",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Ciudad de destino"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="origen",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Ciudad de origen"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="peso_kg",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Peso (kg)"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tiempo_estimado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Tiempo estimado (horas)",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tipo_carga",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="Tipo de carga"
            ),
        ),
    ]
